export const materialesDisponibles = [
  "Botellas PET",
  "Papel",
  "Cartón",
  "Vidrio",
  "Metal",
  "Latas de aluminio",
  "Plástico",
  "Electrónicos",
  "Baterías",
  "Aceite usado",
  "Ropa/Textiles",
  "Orgánicos",
];

export const recyclersData = [
  {
    id: 1,
    nombre: "Juan Pérez",
    tipo: "individual",
    telefono: "71234567",
    whatsapp: "71234567",
    email: "juan@email.com",
    direccion: "Av. América #123",
    zona: "Norte",
    materiales_recoge: ["Botellas PET", "Papel", "Cartón"],
    materiales_ofrece: ["Compost orgánico"],
    rating: 4.5,
    recolecciones: 45,
    descripcion: "Recojo materiales reciclables en zona norte. Servicio a domicilio sin costo adicional.",
    horario: "Lun-Sab 8:00-18:00",
    verificado: true,
  },
  {
    id: 2,
    nombre: "EcoRecicla Bolivia",
    tipo: "empresa",
    empresa: "EcoRecicla SRL",
    telefono: "44123456",
    whatsapp: "71987654",
    email: "contacto@ecorecicla.com",
    direccion: "Calle Sucre #456",
    zona: "Centro",
    materiales_recoge: ["Plástico", "Vidrio", "Metal", "Electrónicos"],
    materiales_ofrece: ["Papel reciclado", "Bolsas ecológicas"],
    rating: 4.8,
    recolecciones: 230,
    descripcion: "Empresa certificada con 10 años de experiencia. Ofrecemos comprobantes y precios competitivos.",
    horario: "Lun-Vie 8:00-19:00, Sáb 9:00-14:00",
    precio_info: "Botellas PET: Bs. 3/kg, Papel: Bs. 1.5/kg",
    verificado: true,
  },
  {
    id: 3,
    nombre: "María González",
    tipo: "individual",
    telefono: "68765432",
    whatsapp: "68765432",
    direccion: "Zona Sud, Calle Los Pinos",
    zona: "Sur",
    materiales_recoge: ["Botellas de vidrio", "Latas de aluminio"],
    materiales_ofrece: [],
    rating: 4.2,
    recolecciones: 28,
    descripcion: "Reciclo vidrio y aluminio. Pago justo por material limpio y separado.",
    horario: "Fines de semana",
    verificado: false,
  },
];